DATA_DIR = "./data"
DEBUG = True

SERVER_ADDRESS = "127.0.0.1"
SERVER_PORT = 5000
SERVER_WEB_URL = f'http://{SERVER_ADDRESS}:{SERVER_PORT}/static/'

SECRET_KEY = 'BT-=f~i1IlIHF(#'
JWT_SECRET = 'R]B+=46,e=gKtI/'

CERT_KEY_FILE = ""
CERT_FILE = ""
